const words = [

    // ===========================================
    // LISTE STRICTE DE MOTS DE 6 LETTRES (SANS ACCENT)
    // ===========================================
    "maison", "python", "ballon", "voyage", "soleil", "enfant", "jardin", "fleurs",
    "regard", "parler", "chante", "courir", "sauter", "tomber", "monter", "chemin",
    "fraise", "orange", "velour", "cadeau", "regles", "fautes", "preuve", "doutes",
    "herbes", "arbres", "nuages", "bonjour", "goutte", "tarder", "faible", "vivant",
    "mortel", "heureux", "triste", "calmer", "poches", "boites", "livres", "cahier",
    "classe", "bureau", "travail", "loisir", "amuser", "ouvrir", "fermer", "pousser",
    "tirer", "lacher", "garder", "achete", "ventes", "argent", "pieces", "billet",
    "banque", "credit", "debite", "compte", "valeur", "minuit", "durant", "touche",
    "sentir", "gouter", "penser", "esprit", "visage", "bouche", "jamber", "coeurx",
    "femmes", "filles", "groupe", "voisin", "villee", "desert", "routes", "ruelle",
    "impasse", "sortie", "entree", "milieu", "centre", "droite", "gauche", "etroit",
    "volume", "poidsx", "lourds", "formes", "courbe", "lignes", "pointu", "epaisse",
    "minces", "blancs", "noires", "rouges", "vertes", "bleues", "jaunes", "grises",
    "brunes", "claire", "foncee", "justes", "morale", "raison", "erreur", "pardon",
    "memoir", "futurs", "unique", "double", "simple", "facile", "moyens", "graves",
    "droles", "riresx", "hurler", "murmur", "signer", "ecrire", "dicter", "clique",
    "ecrans", "ecoute", "bruits", "cloche", "sonner", "tapage", "joieux", "peines",
    "hontex", "jalous", "envies", "amourx", "haines", "gestes", "danser", "siffle",
    "soupir", "pleurs", "baigne", "douche", "propre", "abimes", "repare", "brisee",
    "aidera", "offrir", "rendre", "payera", "donner", "volera", "cachee", "savoir",
    "croire", "douter", "parier", "gagner", "perdre", "tirage", "sortir", "rester",
    "suivre", "verser", "tourne", "marche", "plante", "poussa", "grands", "assezs",
    "petits", "larges", "hautes", "longue", "courte", "epaisx", "finses", "fortes",
    "faibles", "rapide", "lentex", "braves", "sagesx", "fousses", "jeunes",
    "nouvel", "ancien", "premie", "dernier", "proche", "lointx", "loinex", "dessus",
    "devant", "derrie", "dedans", "dehors", "dessou", "hautex", "bassee", "debout",


    // ===========================================
    // LISTE STRICTE DE MOTS DE 7 LETTRES (SANS ACCENT)
    // ===========================================
    "clavier", "voiture", "fenetres", "musique", "chaleur", "bateaux", "cabanees",
    "fromage", "dessert", "cuisine", "histoire", "langues", "science", "voyager",
    "ecrirez", "dessins", "bricole", "chasser", "acheter", "vendrez", "donnera",
    "recevez", "savoirz", "pouvoir", "vouloir", "devoirs", "mettrez", "prendre",
    "reposer", "dormira", "reveils", "matinee", "pausesx", "goutera", "mordrez",
    "bonheur", "douleur", "fortune", "chancez", "risquer", "dangerz", "securis",
    "couvrir", "masquer", "montrer", "devoile", "oublier", "laisser", "appeler",
    "ecouter", "silence", "clameur", "souffle", "respire", "parfumz", "odeurez",
    "saveurs", "pimentz", "mangera", "deguste", "remuiez", "melange", "couperz",
    "cuisinez", "prepare", "termine", "commenc", "arretez", "ralentir", "avancer",
    "reculer", "tournez", "glisser", "marchez", "ramperz", "flotter", "etendre",
    "tisserz", "broderz", "coudrez", "peindre", "graverz", "polirez", "briller",
    "allumer", "couleur", "nuances", "teinter", "pigment", "vitraux", "verriez",
    "metauxx", "pierres", "sableux", "argiles", "pousser", "germerz", "cultive",
    "recolte", "arroser", "insecte", "plantes", "animaux", "oiseaux", "poisson",
    "microbe", "soigner", "guerira", "blesser", "exister", "resiste", "endurer",
    "croitre", "augment", "compare", "jumeaux", "contrer", "similes", "uniques",
    "doubles", "tripler", "entiers", "partiel", "globaux", "regions", "nations",
    "cosmique", "etoiles", "planete", "orbiter", "voyages", "escales", "arriver",
    "departz", "transit", "circulz", "bougera", "bloquer", "chainez", "cordage",
    "relierz", "joindre", "liberez", "prisons", "muraille", "porteur", "fenetre",
    "toiture", "plancher", "piliers", "soutien", "hauteur", "largeur", "etendue",
    "mesurez", "tailles", "dessins", "motifzz", "gravure", "acteurs", "scenics",
    "romance", "poemesx", "lettres", "saisies", "tapeurs", "imprime", "copiere",
    "collers", "sauverz", "quitter", "entriez", "sortira", "passera", "centrez",
    "bordure", "limitez", "extreme", "sommetz", "arriere", "droites", "gauchex",
    "voisins", "eloigne", "proches", "dessous", "dessusx", "devant", "derriere",
    "milieux", "centrez", "entoure", "inclure", "exclure", "inserer", "retirer",
    "ajouter", "enlever", "remplir", "videres", "couvert", "decouvr", "habiter",
    "logerez", "demeure", "adresse", "quartier", "village", "commune", "region",
    "paysage", "continent", "mondees", "univers", "espacez", "distance", "prochez",

    // ===========================================
    // LISTE DE 300 MOTS DE 8 LETTRES (SANS ACCENT)
    // ===========================================
    "abandonne", "abattage", "abattues", "abeilles", "abolirai",
    "abondant", "aboutira", "abritent", "absencee", "absorber",
    "abstrait", "academos", "accorder", "accroche", "accueils",
    "achatons", "acheteur", "acquerir", "actuelle", "admirons",
    "adorable", "adorerai", "affaires", "affiches", "agissons",
    "agissait", "aiguille", "aimerons", "ajoutons", "alarmant",
    "alcooles", "alertons", "alliances", "allonger", "allumons",
    "alterner", "amateurs", "ambiance", "ameliora", "ameneras",
    "amitiees", "amplifie", "amuseras", "analyses", "ancrages",
    "anecdote", "animales", "animerai", "annonces", "annuelle",
    "anonymes", "apporter", "apprends", "approche", "appuient",
    "arbustes", "architect", "argument", "armement", "arracher",
    "arranger", "arrivons", "arrosons", "artistes", "aspirent",
    "assiette", "assiéges", "assurons", "astucieux", "atelierx",
    "attendre", "attirent", "attisons", "attraper", "augmenta",
    "autonomie", "autorise", "avancees", "aventure", "avertira",
    "baguette", "baignade", "baissons", "balayage", "balisees",
    "banlieue", "barriere", "bastions", "bataille", "batiment",
    "batterie", "beaucoup", "benirons", "bienvenu", "billetin",
    "blessure", "bloquant", "bonheurx", "bordures", "bouclier",
    "boucherz", "bougeons", "bouillon", "bouquets", "boutique",
    "branches", "brassage", "brillait", "briserai", "brochure",
    "brulante", "bruyante", "buissons", "cabanons", "cabriols",
    "cacherez", "cadenasx", "cafetera", "cahierzz", "calculer",
    "calories", "cambrure", "campagne", "caniveau", "capitale",
    "caprices", "capturer", "caravane", "carnaval", "carriere",
    "cartable", "cartonne", "cascadee", "casernes", "cassette",
    "causette", "cavernez", "ceinture", "cellules", "cerisier",
    "cerveaux", "chaleurs", "chambrex", "changent", "chantera",
    "chapeaux", "chapelet", "charbonn", "charente", "charriot",
    "chassent", "chattons", "chaussee", "cheminex", "chemises",
    "cherisse", "chercher", "chevauxx", "chevrier", "chiffres",
    "chignons", "chimiques", "chocolat", "choisies", "choquant",
    "chorales", "chuchota", "circuitz", "circuler", "clarifie",
    "claviers", "clochers", "cloitres", "cloturer", "clouages",
    "cochonne", "cocotier", "coffrets", "coiffure", "colereux",
    "colisage", "collines", "colonies", "combattu", "comedien",
    "comparer", "complets", "composes", "comptage", "conduire",
    "confiant", "conflits", "congeles", "conjoint", "connaitre",
    "conseils", "consomme", "contacts", "contrats", "convives",
    "copieuse", "coquille", "cordages", "corniche", "correaux",
    "coteauxz", "coureurs", "courrier", "coutures", "couvreur",
    "craindre", "crayonne", "creature", "creeront", "crevasse",
    "criantes", "criminal", "cristaux", "critique", "croisons",
    "croquette", "croyante", "crucifix", "cruellex", "cuisiner",
    "cultiver", "curioses", "curieuse", "cycliste", "dagobert",
    "danseurs", "dauphins", "debouton", "decembre", "decoller",
    "decrirez", "deduirez", "defendre", "deguster", "dejouant",
    "delaisse", "delicate", "demandes", "demeurez", "demolies",
    "denoncer", "depasser", "depenser", "deployer", "deranger",
    "deroulez", "descente", "dessiner", "detacher", "detruire",
    "devienne", "dialogue", "dictames", "difficil", "digester",
    "diligent", "diplomes", "dirigees", "discours", "discuter",
    "disposer", "dissiper", "divertir", "diviseur", "divisons",
    "domainez", "domicile", "dominent", "donneras", "dopamine",
    "dormirai", "dossiers", "doublons", "douceurs", "draperie",
    "dressons", "dribbler", "duperons", "durables", "dynastie",
    "ecartons", "echanges", "eclairer", "ecolezzs", "ecoutera",
    "ecrivain", "effacera", "efforcer", "egalites", "egoutier",
    "ejectons", "elargies", "elegante", "elirions", "emigrant",
    "emotions", "emporter", "emprunts", "encadres", "encenser",
    "endroits", "enduises", "energiez", "enfances", "enfermer",
    "enflamme", "engendre", "enlevons", "ennemies", "enormous",
    "enseigne", "entendez", "entourer", "entraine", "entrerai",
    "enverrai", "envoyons", "epaisseur", "epanouie", "epelerai",
    "epongesz", "epouvant", "escalade", "escarpes", "esclavee",
    "espacees", "espagnol", "esperant", "essaierez", "essences",
    "estimees", "etablies", "etageres", "etendons", "etonnant",
    "etranger", "etudions", "euphorie", "eviterez", "exactees",
    "examinez", "exercera", "exigeant", "existera", "expliqua",
    "explosif", "explorer", "exposons", "expressz", "fabrique",
    "facilite", "faconnez", "facteurs", "faisable", "familles",
    "farineux", "fasciner", "fatigues", "fauteuil", "favorable",
    "femelles", "feraient", "ferments", "ferraile", "feuillee",
    "fichiers", "figurant", "filmeras", "financez", "finiront",
    "fixation", "flamants", "flaneurs", "fletriss", "flottant",
    "fluteaux", "foisonne", "fondateu", "fondezux", "forceurs",
    "formater", "formules", "fortunes", "fournira", "fretilla",
    "frissons", "frottons", "fruitier", "fuirions", "fumettes",
    "furetant", "fusilier", "gabelles", "galeries", "galettes",
    "garantis", "garderie", "gardezzz", "garnirai", "gastrons",
    "gauchers", "geleezzz", "geniales", "genisses", "gererons",
    "gestions", "glaciers", "glissant", "gouttele", "gouverne",
    "graceful", "graduelz", "graffiti", "grandira", "gratuite",
    "grillade", "grillage", "grossier", "guerrier", "gueulesz",
    "habitons", "hachurer", "hamecons", "haricots", "harmonie",
    "harpiste", "hasarder", "hauteurs", "heroszzz", "hibiscus",
    "hivernez", "hommages", "honorons", "horizons", "horrible",
    "houblons", "humaines", "humidite", "hypothese",

    // ===========================================
    // LISTE STRICTE DE MOTS DE 9 LETTRES (SANS ACCENT)
    // ===========================================
    "telephone", "tristesse", "quartiers", "distances", "voyageurs",
    "inventions", "armistice", "harmonies", "uniformes", "originale",
    "imitatifs", "coloniale", "ratifions", "corporels", "passionne",
    "endurante", "courageux", "franchise", "fidelites", "jalousies",
    "explorons", "imaginate", "serenites", "consolons", "soutenons",
    "victimees", "officiers", "travaille", "activites", "affirmera",
    "confirmee", "combattre", "attaquons", "felicitez", "secourons",
    "assisters", "meditativ", "alliancee", "resisters", "reussirez",
    "bravourex", "amoureuxs", "paysannes", "voyageuse", "discutees",
    "programer", "calculons", "etudiants", "vacanciers", "semainees",
    "cuisinier", "mecanique", "boulanger", "charcuter", "piscineur",
    "agriculte", "nourrirai", "enseignes", "facturier", "imprimeur",
    "journalis", "redaction", "informati", "ordinateur", "naviguons",
    "surfeuses", "developpe", "gestionna", "comptable", "secretaire",
    "directeur", "president", "ambassade", "ministere", "prefecture",
    "municipal", "conseiller", "avocatise", "magistrat", "tribunaux",
    "audiences", "arbitreux", "justiceux", "criminale", "policiere",
    "detective", "gardienne", "prisonner", "liberator", "militaire",
    "strateges", "commandes", "capitaine", "lieutenant", "colonelle",
    "generalex", "mariniere", "aviateurs", "soldatise", "combattre",
    "explosion", "incendies", "urgencees", "ambulance", "hopitauxx",
    "chirurgix", "doctrices", "maladieux", "soigneurs", "vaccinate",
    "remedions", "pharmacie", "dentistes", "patientsx", "consultat",
    "traitions", "examinons", "diagnosti", "symptomes", "epidemies",
    "pandemiex", "confinons", "soignants", "reanimation", "operation",
    "nourrisse", "enfantsxx", "adolescent", "adulthood", "vieillese",
    "retraitee", "anciennes", "familleux", "parentsxx", "cousinage",
    "mariageux", "divorcera", "relationx", "amicalite", "solidarit",
    "fraternel", "partenari", "associati", "collectif", "compagnon",
    "collegues", "travaille", "ouvriersx", "ingenieur", "architect",
    "construct", "immobilier", "banquierx", "caissiers", "vendeuses",
    "serveuses", "chauffeur", "conducteu", "piloteurs", "voyageons",
    "touristes", "explorate", "aventures", "randonnex", "alpinisme",
    "nautiques", "sportives", "gymnastes", "boxeusesx", "footballe",
    "tennismen", "cyclistes", "patineurs", "natations", "plongeurs",
    "musiciens", "chanteurs", "danseuses", "peintures", "sculpture",
    "photograp", "journalis", "ecrivains", "poetesses", "acteurise",
    "comedienx", "realiseux", "scenarist", "producteu", "spectacle",
    "theatrale", "cinematre", "festivalx", "cultureux", "museeuses",
    "expositio", "peinturex", "collection", "bibliothe", "litterair",
    "romanciers", "histoires", "documenta", "recherche", "scientif",
    "biologiste", "chimistes", "physicien", "astronomx", "mathemati",
    "ecologiste", "geologiste", "technolog", "robotique", "numerique",
    "internetx", "reseaures", "logiciels", "serveures", "stockages",
    "securites", "cryptages", "programme", "algorithx", "donneeuse",
    "traitemen", "systemeex", "plateform", "application", "interface",
    "connexion", "utilisons", "navigatio", "telecharg", "partageur",
    "messageri", "reseauxxx", "diffusion", "streaming", "videochat",
    "conference", "reunionsx", "webinaire", "formation", "education",
    "universit", "enseignon", "professeu", "apprentix", "etudiante",
    "examinate", "concoursx", "certificat", "diplomate", "brevetage",
    "licencies", "doctorant", "recherchx", "publierai", "revueuses",
    "editeursx", "imprimons", "auteursxx", "traduirix", "linguiste",
    "grammatic", "orthograp", "vocabular", "synonymes",
    "antonymes", "expressee", "communiqu", "discourir", "dialogues",
    "discussion", "negocierx", "contratxx", "accordons", "partenai",
    "collabore", "integration", "developpe", "innovation", "creationx",
    "production", "distribution", "marketing", "publicite", "campagnes",
    "strategie", "planifies", "gestionna", "budgetair", "financiere",
    "investiss", "epargneux", "assurance", "banquiers", "creditent",
    "emprunter", "debiteurs", "reveneurs", "depensons", "economies",

    // ===========================================
    // LISTE STRICTE DE MOTS DE 10 LETTRES (SANS ACCENT)
    // ===========================================
    "javascript", "incroyable", "intelligent", "impossible", "necessaire",
    "difference", "experience", "appartement", "temperature", "ventilation",
    "electricite", "batteries", "vehicules", "conducteur", "passagers",
    "celebration", "anniversaire", "funerailles", "promesses", "generosite",
    "solidarite", "fraternite", "humanisme", "benevolat", "fondation",
    "initiative", "partenariat", "compromis", "resolution", "revolution",
    "stagnation", "croissance", "logistique", "transport", "ingenierie",
    "relaxation", "meditation", "personnal", "caractere", "modernite",
    "futuriste", "resistant", "tranquille", "industrie", "agriculture",
    "protection", "performance", "transition", "judicieuse", "pertinente",
    "entretien", "fonctionner", "discipliner", "techniques", "partenaires",
    "particuliers", "abonnement", "adaptation", "admission", "adventurer",
    "agriculture", "alternatif", "amendement", "animation", "appliquer",
    "apporteurs", "appreciate", "approbation", "argumenter", "arrestation",
    "assemblage", "assistance", "assureur", "atelierier", "attraction",
    "auditeurs", "authentique", "autorisation", "aventuriers", "avertisseur",
    "balanceuse", "banquieres", "baptiseront", "battements", "beaucoupent",
    "beneficent", "biscuiterie", "blanchiment", "bouleverse", "brillantine",
    "budgetaire", "bureautique", "calculateur", "capitulaire", "capitalise",
    "caractérisé", "carrossier", "casseroles", "catholiques", "celebration",
    "célébration", "centraliser", "centrauxent", "certification", "champignon",
    "changements", "charpentier", "chiffrement", "chirurgiens", "chocolater",
    "circulation", "civilisation", "climatisation", "cohabitation", "collection",
    "colleagues", "colonisateurs", "combattants", "commandants", "commercials",
    "communiquer", "comparaison", "compatibles", "compensation", "competences",
    "compétitives", "compléments", "comportement", "composantes", "comprendre",
    "compromises", "computables", "concentration", "concepteur", "conception",
    "concession", "concurrence", "conditionner", "conférence", "confrontent",
    "congédiement", "connaissances", "conservation", "consolidera", "constituant",
    "constitution", "construction", "consultation", "consulteras", "contamination",
    "contenances", "contentions", "contestable", "contraction", "contributeur",
    "convainquant", "conversation", "conversion", "convivialité", "coordination",
    "corporation", "correcteurs", "correspondre", "correction", "côtisation",
    "côtiseraient", "courageuses", "croyances", "cultivation", "cultivateur",
    "curiosités", "déchargement", "déclaration", "développement", "démonstratif",
    "dentistes", "départements", "déplacement", "dépression", "détection", "différentes",
    "difficultés", "diminution", "directionnel", "discipliner", "distributeur",
    "divertissement", "documentation", "données", "douze", "durabilité",
    "éducationnel", "effectivement", "élévation", "émancipation", "émission",
    "emplacement", "encouragement", "enregistrement", "enseignement", "entraînement",
    "entrepreneurs", "entretienner", "entourages", "environnement", "équipement",
    "équitables", "espionnage", "estimation", "établissement", "éteindre",
    "évaluation", "événement", "examinations", "exécution", "expérimenté",
    "expédition", "explicatif", "exploration", "exploitation", "expression",
    "exterminer", "fabrication", "facilitateurs", "facturation", "fascinantes",
    "fédérations", "fermetures", "ferronnerie", "fictivement", "filtrations",
    "financement", "fonctionner", "fondations", "formation", "formulaires",
    "fournisseur", "fréquentent", "fréquentiel", "fonctionnaire",

    // ===========================================
    // LISTE STRICTE DE MOTS DE 11 LETTRES (SANS ACCENT)
    // ===========================================
    "application",
    "information",
    "organisation",
    "satisfaction",
    "repartition",
    "maintenance",
    "installation",
    "documentation",
    "certification",
    "autorisation",
    "negociation",
    "partenariat",
    "collaboration",
    "cooperation",
    "determination",
    "preparation",
    "planification",
    "strategique",
    "financement",
    "distribution",
    "production",
    "fabrication",
    "conception",
    "technologie",
    "operationnel",
    "fonctionnel",
    "specifique",
    "techniciens",
    "specialiste",
    "professionnel",
    "universitaire",
    "experimente",
    "illustration",
    "promotionnel",
    "fournisseur",
    "coordination",
    "delegation",
    "autoritaire",
    "democratique",
    "reglementaire",
    "standardiser",
    "qualitative",
    "quantitative",
    "representant",
    "comparaison",
    "rhetorique",
    "resistance",
    "flexibilite",
    "rigidement",
    "contrastes",
    "harmoniques",
    "rythmiques",
    "melodiques",
    "referencemen",
    "intellectuel",
    "capacitaire",
    "limitations",
    "potentielle",
    "decisionnel",
    "developpement",
    "creativite",
    "consultation",
    "prediction",
    "statistique",
    "concurrence",
    "anticipation",
    "interpretation",
    "redactionnel",
    "perceptuelle",
    "sensationnel",
    "communication",
    "environnement",
    "transporteur",
    "caracteriste",
    "responsable",
    "transformation",
    "exploitation",
    "fonctionnaire",
    "investissement",
    "industrielle",
    "agriculteurs",
    "construction",
    "reorganisation",
    "international",
    "particularite",
    "demonstration",
    "implementation",
    "administratif",
    "conseilleres",
    "evaluation",
    "amelioration",
    "productivite",
    "organisation",
    "realisations",
    "diversification",
    "commercialise",
    "modernisation",
    "personnalise",
    "optimisation",
    "responsables",
    "collaborative",
    "organisation",
    "partenariats",
    "technicienne",
    "developpement",
    "experimentale",
    "communication",
    "innovationnel",
    "investisseurs",
    "representation",
    "connaissance",
    "documentation",
    "rechercheurs",
    "developpeurs",
    "competences",
    "formulation",
    "programmatique",
    "anticipation",
    "calculatoire",
    "interpretive",
    "previsionnel",
    "decisionnaire",
    "gestionnaire",
    "approvisionnement",
    "transformation",
    "ameliorations",
    "reorganisation",
    "administration",
    "caracteristique",
    "cooperationnel",
    "collaborateurs",
    "ameliorativement",
    "restructuration",
    "professionnelle",
    "technologique",
    "identification",
    "collaboration",
    "implementation",
    "administratives"
]